// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusHome.IoT.Infrastructure.Data;

#nullable disable

namespace NexusHome.IoT.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    partial class SmartHomeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.BatteryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChargeLevelPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentReading")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("CycleCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MeasurementTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperationMode")
                        .HasColumnType("int");

                    b.Property<int>("SmartHomeDeviceId")
                        .HasColumnType("int");

                    b.Property<decimal>("StateOfHealthPercentage")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VoltageReading")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeDeviceId");

                    b.ToTable("BatteryStatuses");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.DeviceAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmartHomeDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeDeviceId", "CreatedAt");

                    b.ToTable("DeviceAlerts");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.DeviceEnergyConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppliedTariffRate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CalculatedCostAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("CarbonFootprintGrams")
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentReading")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("EnergySource")
                        .HasColumnType("int");

                    b.Property<decimal>("FrequencyReading")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MeasurementTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PowerConsumptionKilowattHours")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("PowerFactorReading")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("PowerQualityIndicator")
                        .HasColumnType("int");

                    b.Property<int>("SmartHomeDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VoltageReading")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeDeviceId", "MeasurementTimestamp");

                    b.ToTable("EnergyConsumptions");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.DeviceMaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmartHomeDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeDeviceId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.DeviceTelemetryReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReadingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmartHomeDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeDeviceId");

                    b.ToTable("DeviceTelemetryReading");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.EnergyOptimizationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComfortImpactThreshold")
                        .HasColumnType("int");

                    b.Property<string>("ConditionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetSavingsPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalAccumulatedSavings")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EnergyOptimizationRules");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.IntelligentAutomationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastExecuted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SerializedActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerializedConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SmartHomeDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeDeviceId");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.SmartHomeDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalMetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BatteryLevel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ConnectionProtocol")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CurrentPowerConsumption")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("DeviceConfigurationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DeviceFriendlyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareVersionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrentlyOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCommunicationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MaximumPowerRating")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MqttTopicPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NetworkSignalStrength")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextScheduledMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OperatingTemperature")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("PhysicalLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoomAssignment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SecurityStatus")
                        .HasColumnType("int");

                    b.Property<string>("UniqueDeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UniqueDeviceIdentifier")
                        .IsUnique();

                    b.ToTable("SmartDevices");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.SolarGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EfficiencyPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("IrradianceWattsPerSquareMeter")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MeasurementTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PowerGeneratedKilowatts")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("SmartHomeDeviceId")
                        .HasColumnType("int");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeDeviceId");

                    b.ToTable("SolarGenerations");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preferences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.BatteryStatus", b =>
                {
                    b.HasOne("NexusHome.IoT.Core.Domain.SmartHomeDevice", "SmartHomeDevice")
                        .WithMany()
                        .HasForeignKey("SmartHomeDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartHomeDevice");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.DeviceAlert", b =>
                {
                    b.HasOne("NexusHome.IoT.Core.Domain.SmartHomeDevice", "SmartHomeDevice")
                        .WithMany("GeneratedAlerts")
                        .HasForeignKey("SmartHomeDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartHomeDevice");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.DeviceEnergyConsumption", b =>
                {
                    b.HasOne("NexusHome.IoT.Core.Domain.SmartHomeDevice", "SmartHomeDevice")
                        .WithMany("EnergyConsumptionHistory")
                        .HasForeignKey("SmartHomeDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartHomeDevice");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.DeviceMaintenanceRecord", b =>
                {
                    b.HasOne("NexusHome.IoT.Core.Domain.SmartHomeDevice", "SmartHomeDevice")
                        .WithMany("MaintenanceHistory")
                        .HasForeignKey("SmartHomeDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartHomeDevice");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.DeviceTelemetryReading", b =>
                {
                    b.HasOne("NexusHome.IoT.Core.Domain.SmartHomeDevice", "SmartHomeDevice")
                        .WithMany("TelemetryReadings")
                        .HasForeignKey("SmartHomeDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartHomeDevice");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.IntelligentAutomationRule", b =>
                {
                    b.HasOne("NexusHome.IoT.Core.Domain.SmartHomeDevice", "SmartHomeDevice")
                        .WithMany("AssociatedAutomationRules")
                        .HasForeignKey("SmartHomeDeviceId");

                    b.Navigation("SmartHomeDevice");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.SolarGeneration", b =>
                {
                    b.HasOne("NexusHome.IoT.Core.Domain.SmartHomeDevice", "SmartHomeDevice")
                        .WithMany()
                        .HasForeignKey("SmartHomeDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartHomeDevice");
                });

            modelBuilder.Entity("NexusHome.IoT.Core.Domain.SmartHomeDevice", b =>
                {
                    b.Navigation("AssociatedAutomationRules");

                    b.Navigation("EnergyConsumptionHistory");

                    b.Navigation("GeneratedAlerts");

                    b.Navigation("MaintenanceHistory");

                    b.Navigation("TelemetryReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
